### ISSUE TITLE
scaling text width in fullscreen mode

### ISSUE THREAD

**Issue by skellis46** [Razumihin/obsidian-fullscreen-plugin#4]
Hi 
Thanks so much for your work on this plugin. I use it a lot. I'm wondering if it's possible to increase the width of the text block when in fullscreen mode. That mode gives me more space around the outside of the text so being able to alter that width would be super useful (especially if I scale up the size of the text). 
Hope this makes sense.
Cheers
Simon

**Comment by Razumihin** [comment]
The text width scaling is done in the obsidian theme css file with something like this: 

```css
.markdown-source-view, .markdown-preview-view {
max-width: 900px;
margin: auto;
}
```

also it's overwritten by a setting in Settings->Editor->Readable line length that can be toggled so that the full width can be utilized. 

I'm not sure how i'd add this to the plugins' config so that it'd be useful, but modifying these values should affect the plugin too.

**Comment by skellis46** [comment]
thanks so much. I figured this might be the case. Cheers, Simon
